version: 0.2

phases:
  install:
    commands:
      - echo Instalando dependencias...
  pre_build:
    commands:
      - echo Login en Docker...
      # Aquí iría el login a ECR si fueras a subir la imagen
  build:
    commands:
      - echo Construyendo la imagen de Docker...
      - docker build -t mi-programa-python .
      - echo Ejecutando el contenedor...
      # Ejecutamos el contenedor para procesar los datos
      - docker run --name ejecucion-tarea mi-programa-python
  post_build:
    commands:
      - echo Extrayendo resultados del contenedor...
      # Copiamos los archivos generados dentro del contenedor hacia afuera
      - docker cp ejecucion-tarea:/app/resultados.txt .
      - docker cp ejecucion-tarea:/app/backup.log .
      - echo Proceso finalizado el `date`

artifacts:
  files:
    - resultados.txt
    - backup.log