version: 0.2

phases:
  pre_build:
    commands:
      - echo Iniciando fase de Pre-build...
      - ls -R  # Esto sirve para verificar que CodeBuild ve tus carpetas
  build:
    commands:
      - echo Construyendo la imagen de Docker...
      - docker build -t mi-app-python .
      - echo Ejecutando el contenedor...
      # CAMBIO AQUÍ: Eliminamos 'app/' porque el archivo ya está en la raíz del WORKDIR
      - docker run --name ejecucion-proyecto mi-app-python python programa.py "Version_Final_Examen"
  post_build:
    commands:
      - echo Extrayendo el log del contenedor...
      # Copiamos el log generado dentro de la carpeta app del contenedor hacia afuera
      - docker cp ejecucion-proyecto:/app/backup.log ./backup.log
      - echo Subiendo log a S3...
      - aws s3 cp backup.log s3://ebani-act-devops/backup.log

artifacts:
  files:
    - backup.log
    - app/resultados.txt